"""Terraform file renderers for Cloudflare Free-plan bootstrap.

Each render_*() function returns a string of valid HCL.
All generated files use 2-space indentation (validated in tests).

Provider: cloudflare/cloudflare ~> 5
Refs:
  https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs
  https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/workers_script
  https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/r2_bucket
  https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/d1_database
  https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/workers_kv_namespace
"""
from __future__ import annotations


def render_provider() -> str:
    """Render provider.tf — API token auth via env / variable."""
    return """\
# Generated by cloudbooter-cloudflare — do not edit manually.
# Re-run setup_cloudflare_terraform.sh to regenerate.

terraform {
  required_version = ">= 1.6.0"
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5"
    }
  }
}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}
"""


def render_variables(
    account_id: str,
    worker_name: str = "cloudbooter-worker",
    workers_cpu_ms: int = 10,
    r2_bucket_name: str = "cloudbooter-r2",
    r2_storage_class: str = "Standard",
    d1_database_name: str = "cloudbooter-db",
    kv_namespace_title: str = "cloudbooter-kv",
    zone_id: str = "",
    include_zone: bool = False,
) -> str:
    """Render variables.tf including free-tier check blocks."""

    zone_vars = ""
    zone_checks = ""
    if include_zone or zone_id:
        zone_vars = f"""
variable "zone_id" {{
  description = "Optional Cloudflare zone ID for custom-domain routes"
  type        = string
  default     = "{zone_id}"
}}
"""

    return f"""\
# Generated by cloudbooter-cloudflare — do not edit manually.

variable "cloudflare_api_token" {{
  description = "Cloudflare API token (or set CLOUDFLARE_API_TOKEN env — provider also reads it)"
  type        = string
  sensitive   = true
  default     = ""
}}

variable "account_id" {{
  description = "Cloudflare account ID"
  type        = string
  default     = "{account_id}"
}}

variable "worker_name" {{
  description = "Workers script name (also used for workers.dev subdomain label)"
  type        = string
  default     = "{worker_name}"
}}

variable "workers_cpu_ms" {{
  description = "Workers CPU time limit in ms (Free plan: 10)"
  type        = number
  default     = {workers_cpu_ms}
}}

variable "r2_bucket_name" {{
  description = "R2 bucket name"
  type        = string
  default     = "{r2_bucket_name}"
}}

variable "r2_storage_class" {{
  description = "R2 storage class (Free-safe: Standard)"
  type        = string
  default     = "{r2_storage_class}"
}}

variable "d1_database_name" {{
  description = "D1 database name"
  type        = string
  default     = "{d1_database_name}"
}}

variable "kv_namespace_title" {{
  description = "Workers KV namespace title"
  type        = string
  default     = "{kv_namespace_title}"
}}

variable "enable_workers_dev" {{
  description = "Enable workers.dev subdomain for the Worker"
  type        = bool
  default     = true
}}

variable "do_backend" {{
  description = "Durable Objects storage backend (Free: sqlite only)"
  type        = string
  default     = "sqlite"
}}

variable "enable_load_balancer" {{
  description = "Whether to create a Load Balancer (billable — blocked by check)"
  type        = bool
  default     = false
}}
{zone_vars}
# ── Free-Tier Guard: check blocks ─────────────────────────────────────────────

check "workers_cpu_free_tier" {{
  assert {{
    condition     = var.workers_cpu_ms <= 10
    error_message = "Workers Free plan CPU limit is 10 ms. Got: ${{var.workers_cpu_ms}}"
  }}
}}

check "r2_storage_class_free_tier" {{
  assert {{
    condition     = var.r2_storage_class == "Standard"
    error_message = "R2 Free-safe storage class is Standard. Got: ${{var.r2_storage_class}}"
  }}
}}

check "do_backend_free_tier" {{
  assert {{
    condition     = var.do_backend == "sqlite"
    error_message = "Durable Objects on Free plan require sqlite backend. Got: ${{var.do_backend}}"
  }}
}}

check "load_balancer_blocked" {{
  assert {{
    condition     = var.enable_load_balancer == false
    error_message = "Cloudflare Load Balancers are billable and blocked by default."
  }}
}}
{zone_checks}"""


def render_worker_script() -> str:
    """Minimal ESM Worker source written alongside Terraform."""
    return """\
// Generated by cloudbooter-cloudflare — free-tier hello Worker
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    return new Response(
      JSON.stringify({
        ok: true,
        provider: "cloudflare",
        path: url.pathname,
        hasKV: Boolean(env.KV),
        hasR2: Boolean(env.R2),
        hasD1: Boolean(env.DB),
      }),
      {
        headers: { "content-type": "application/json; charset=utf-8" },
      }
    );
  },
};
"""


def render_main(
    include_kv: bool = True,
    include_r2: bool = True,
    include_d1: bool = True,
    include_workers_dev: bool = True,
) -> str:
    """Render main.tf — Worker + optional free-tier bindings."""

    kv_resource = ""
    kv_binding = ""
    if include_kv:
        kv_resource = """
# ── Workers KV ──────────────────────────────────────────────────────────────

resource "cloudflare_workers_kv_namespace" "kv" {
  account_id = var.account_id
  title      = var.kv_namespace_title
}
"""
        kv_binding = """
    {
      name         = "KV"
      type         = "kv_namespace"
      namespace_id = cloudflare_workers_kv_namespace.kv.id
    },"""

    r2_resource = ""
    r2_binding = ""
    if include_r2:
        r2_resource = """
# ── R2 Bucket ───────────────────────────────────────────────────────────────

resource "cloudflare_r2_bucket" "bucket" {
  account_id    = var.account_id
  name          = var.r2_bucket_name
  storage_class = var.r2_storage_class
}
"""
        r2_binding = """
    {
      name        = "R2"
      type        = "r2_bucket"
      bucket_name = cloudflare_r2_bucket.bucket.name
    },"""

    d1_resource = ""
    d1_binding = ""
    if include_d1:
        d1_resource = """
# ── D1 Database ─────────────────────────────────────────────────────────────

resource "cloudflare_d1_database" "db" {
  account_id = var.account_id
  name       = var.d1_database_name
}
"""
        d1_binding = """
    {
      name        = "DB"
      type        = "d1"
      database_id = cloudflare_d1_database.db.id
    },"""

    workers_dev = ""
    if include_workers_dev:
        workers_dev = """
# ── workers.dev subdomain ───────────────────────────────────────────────────

resource "cloudflare_workers_script_subdomain" "workers_dev" {
  account_id       = var.account_id
  script_name      = cloudflare_workers_script.app.script_name
  enabled          = var.enable_workers_dev
  previews_enabled = var.enable_workers_dev
}
"""

    return f"""\
# Generated by cloudbooter-cloudflare — do not edit manually.
{kv_resource}{r2_resource}{d1_resource}
# ── Workers Script ──────────────────────────────────────────────────────────

resource "cloudflare_workers_script" "app" {{
  account_id  = var.account_id
  script_name = var.worker_name
  main_module = "worker.mjs"
  content_file = "${{path.module}}/worker.mjs"
  content_sha256 = filesha256("${{path.module}}/worker.mjs")

  compatibility_date = "2026-07-01"

  limits = {{
    cpu_ms = var.workers_cpu_ms
  }}

  bindings = [{kv_binding}{r2_binding}{d1_binding}
  ]
}}
{workers_dev}
# ── Outputs ─────────────────────────────────────────────────────────────────

output "worker_name" {{
  description = "Deployed Workers script name"
  value       = cloudflare_workers_script.app.script_name
}}

output "workers_dev_hint" {{
  description = "workers.dev URL pattern (subdomain is account-specific)"
  value       = "https://${{var.worker_name}}.<your-subdomain>.workers.dev"
}}

output "account_id" {{
  description = "Cloudflare account ID"
  value       = var.account_id
}}
"""


def render_kv() -> str:
    """Optional standalone kv.tf (when splitting services)."""
    return """\
# Generated by cloudbooter-cloudflare — optional KV module.

resource "cloudflare_workers_kv_namespace" "kv" {
  account_id = var.account_id
  title      = var.kv_namespace_title
}
"""


def render_r2() -> str:
    """Optional standalone r2.tf."""
    return """\
# Generated by cloudbooter-cloudflare — optional R2 module.

resource "cloudflare_r2_bucket" "bucket" {
  account_id    = var.account_id
  name          = var.r2_bucket_name
  storage_class = var.r2_storage_class
}
"""


def render_d1() -> str:
    """Optional standalone d1.tf."""
    return """\
# Generated by cloudbooter-cloudflare — optional D1 module.

resource "cloudflare_d1_database" "db" {
  account_id = var.account_id
  name       = var.d1_database_name
}
"""
